export type FaqLanguage = 'en' | 'fil';

export type FaqAction = {
  label: { en: string; fil: string };
  route: string;
};

export type AniFaq = {
  id: string;
  topic: 'using' | 'match' | 'money' | 'outlets' | 'saved' | 'offline';
  question: { en: string; fil: string };
  answer: { en: string; fil: string };
  aliases: string[];
  routes?: string[];
  action?: FaqAction;
};

export type FaqMatch =
  | { kind: 'answer'; faq: AniFaq; score: number }
  | { kind: 'choices'; faqs: AniFaq[] }
  | { kind: 'none' };

export const ANI_FAQ_VERSION = 1;

const q = (en: string, fil: string) => ({ en, fil });

export const ANI_FAQS: AniFaq[] = [
  { id: 'what-is-aniwhere', topic: 'using', question: q('What is AniWhere?', 'Ano ang AniWhere?'), answer: q('AniWhere helps you find possible places for your harvest in Laguna. It compares crop fit, quantity, sample prices, distance, and what you still need to confirm. It does not guarantee a sale.', 'Tinutulungan ka ng AniWhere na makahanap ng posibleng mapagbebentahan ng ani sa Laguna. Ikinukumpara nito ang fit ng pananim, dami, halimbawang presyo, layo, at mga dapat kumpirmahin. Hindi ito garantiya ng bentahan.'), aliases: ['what is aniwhere', 'ano ang aniwhere', 'how does aniwhere work', 'paano gumagana aniwhere'], routes: ['*'] },
  { id: 'enter-harvest', topic: 'using', question: q('How do I enter my harvest?', 'Paano ilagay ang ani ko?'), answer: q('Start at Harvest, choose the crop, enter the amount in kg, choose your municipality, and select the ready date. Add optional details only when they help explain your harvest.', 'Sa Ani ko, piliin ang pananim, ilagay ang dami sa kg, piliin ang munisipyo, at ilagay ang petsa kung kailan handa. Magdagdag lang ng detalye kung makatutulong ito sa pagpapaliwanag ng ani.'), aliases: ['enter harvest', 'add harvest', 'ilagay ang ani', 'maglagay ng ani', 'where do i start'], routes: ['/'], action: { label: q('Enter harvest', 'Ilagay ang ani'), route: '/' } },
  { id: 'edit-harvest', topic: 'using', question: q('How do I change my harvest details?', 'Paano baguhin ang detalye ng ani?'), answer: q('Choose Edit harvest or Ani ko, update the crop, amount, place, or date, then search again. Your harvest context is kept in the link while you move through the results.', 'Piliin ang Baguhin ang ani o Ani ko, ayusin ang pananim, dami, lugar, o petsa, at maghanap muli. Nananatili sa link ang detalye ng ani habang tinitingnan mo ang mga resulta.'), aliases: ['edit harvest', 'change harvest', 'baguhin ang ani', 'i-edit ang ani', 'change my details'], routes: ['*'], action: { label: q('Edit harvest', 'Baguhin ang ani'), route: '/' } },
  { id: 'no-results', topic: 'using', question: q('Why did I get no results?', 'Bakit walang resulta?'), answer: q('Check the crop, amount, municipality, date, and any filters. A crop may have no compatible demo outlet, the link may be invalid, or the available information may be incomplete. Try correcting the harvest details or choose another crop amount.', 'Suriin ang pananim, dami, munisipyo, petsa, at mga filter. Maaaring walang tugmang demo outlet, may mali sa link, o kulang ang impormasyon. Ayusin ang detalye ng ani o subukan ang ibang dami o pananim.'), aliases: ['no results', 'nothing found', 'walang resulta', 'walang lumabas', 'why no buyers', 'bakit walang buyer'], routes: ['/discover'], action: { label: q('Review harvest', 'Suriin ang ani'), route: '/' } },

  { id: 'full-match', topic: 'match', question: q('What does Matches your harvest mean?', 'Ano ang ibig sabihin ng Tugma sa ani?'), answer: q('AniWhere found enough recorded evidence for the outlet to accept your full entered quantity without an explicit conflict. It is still a planning result, not a sale, reservation, or promise from the outlet. Confirm current capacity, price, quality requirements, and receiving terms before travel.', 'May sapat na nakatalang ebidensya ang AniWhere na kayang tanggapin ng outlet ang buong daming inilagay mo at walang malinaw na conflict. Gabay pa rin ito sa pagpaplano, hindi bentahan, reservation, o pangako ng outlet. Kumpirmahin ang kasalukuyang kapasidad, presyo, quality requirements, at receiving terms bago bumiyahe.'), aliases: ['matches your harvest', 'full match', 'buong tugma', 'tugma sa ani', 'buong ani', 'accept all', 'tanggap lahat'], routes: ['/discover', '/places'] },
  { id: 'partial-match', topic: 'match', question: q('What does Accepts part of your harvest mean?', 'Ano ang ibig sabihin ng Tumatanggap ng bahagi?'), answer: q('The recorded active offer can take only part of your entered harvest. AniWhere shows the accepted quantity and the quantity that would remain. Only the accepted quantity should be used for any proceeds calculation, and you should still confirm the current offer before travel.', 'Bahagi lang ng inilagay mong ani ang kayang tanggapin ng nakatalang aktibong offer. Ipinapakita ng AniWhere ang matatanggap na dami at ang matitirang dami. Ang matatanggap na dami lang ang dapat gamitin sa pagkalkula ng halaga, at kailangan pa ring kumpirmahin ang kasalukuyang offer bago bumiyahe.'), aliases: ['accepts part of your harvest', 'partial match', 'bahagi ng ani', 'tumatanggap ng bahagi', 'part of my harvest', 'partial', 'tugmang bahagi'], routes: ['/discover', '/places'] },
  { id: 'confirm-match', topic: 'match', question: q('What does Contact to confirm mean?', 'Ano ang ibig sabihin ng Kumpirmahin muna?'), answer: q('The crop may be relevant, but AniWhere is missing an important current fact such as capacity, schedule, quality, or active demand. Treat that fact as unknown and contact the outlet before loading or travelling.', 'Maaaring relevant ang pananim, pero may mahalagang kasalukuyang detalye na hindi alam ng AniWhere gaya ng kapasidad, schedule, quality, o aktibong demand. Ituring muna itong hindi alam at kontakin ang outlet bago maghakot o bumiyahe.'), aliases: ['contact to confirm', 'confirm first', 'confirm match', 'kumpirmahin muna', 'need confirmation', 'suriin muna'], routes: ['/discover', '/places'] },
  { id: 'can-accept', topic: 'match', question: q('Can an outlet accept my harvest?', 'Matatanggap ba ng outlet ang ani ko?'), answer: q('The fit label is based on the recorded crop and capacity. It does not confirm a live purchase. Use the outlet contact preparation and confirm crop condition, quantity, price, date, and receiving hours.', 'Batay ang fit label sa nakatalang pananim at kapasidad. Hindi nito kinukumpirma ang aktuwal na pagbili. Gamitin ang contact preparation at kumpirmahin ang kondisyon ng pananim, dami, presyo, petsa, at oras ng pagtanggap.'), aliases: ['can accept', 'will they buy', 'tumatanggap ba', 'bibili ba', 'can buyer accept'], routes: ['/discover', '/places'] },
  { id: 'harvest-remaining', topic: 'match', question: q('How much harvest will remain?', 'Gaano karaming ani ang matitira?'), answer: q('When accepted quantity is known, remaining harvest is your entered quantity minus that accepted quantity. If capacity is unknown, AniWhere keeps the remaining quantity unknown instead of pretending the whole harvest matches.', 'Kapag alam ang matatanggap na dami, ang matitirang ani ay daming inilagay mo bawas sa matatanggap na dami. Kung hindi alam ang kapasidad, mananatiling hindi alam ang matitirang dami sa halip na sabihing tugma ang buong ani.'), aliases: ['harvest remaining', 'how much remains', 'matitirang ani', 'magkano matitira', 'remaining quantity'], routes: ['/discover', '/places'] },
  { id: 'match-not-guarantee', topic: 'match', question: q('Does a match guarantee a sale?', 'Garantisado ba ang bentahan kapag may match?'), answer: q('No. A match is a decision aid from available records. It does not reserve capacity, confirm a buyer, or guarantee payment. Confirm directly before travelling.', 'Hindi. Gabay sa desisyon ang match batay sa available na tala. Hindi ito reservation, kumpirmasyon ng buyer, o garantiya ng bayad. Kumpirmahin muna bago bumiyahe.'), aliases: ['match guarantee', 'guarantee sale', 'guaranteed buyer', 'garantiya ng bentahan', 'sigurado bang bibilhin'], routes: ['*'] },

  { id: 'sample-price', topic: 'money', question: q('Is the price live?', 'Live ba ang presyo?'), answer: q('Not necessarily. AniWhere distinguishes demo or reference prices from buyer-posted offers, and expired offers are not active demand. Check the evidence label and date, then confirm the current buyer price before deciding.', 'Hindi palagi. Hinihiwalay ng AniWhere ang demo o reference price sa buyer-posted offer, at hindi aktibong demand ang expired na offer. Tingnan ang evidence label at petsa, saka kumpirmahin ang kasalukuyang presyo ng buyer bago magdesisyon.'), aliases: ['sample price', 'price live', 'current price', 'halimbawang presyo', 'presyo ngayon', 'live price'], routes: ['/discover', '/places', '/compare'] },
  { id: 'gross-subtotal', topic: 'money', question: q('What is gross subtotal?', 'Ano ang gross subtotal?'), answer: q('Gross subtotal is the estimated accepted quantity multiplied by the listed price per kg. It is before transport and other farm costs, and it is not profit.', 'Ang gross subtotal ay tinatayang matatanggap na dami na minultiply sa nakalistang presyo bawat kilo. Bago ito sa transport at iba pang gastos, kaya hindi ito tubo.'), aliases: ['gross subtotal', 'gross amount', 'kabuuang halaga', 'gross na halaga'], routes: ['/places', '/compare'] },
  { id: 'transport-expense', topic: 'money', question: q('Where does the transport amount come from?', 'Saan galing ang halaga ng transport?'), answer: q('It may begin as a sample transport estimate from the app or use the amount you enter. Blank means unknown; zero means you intentionally entered ₱0. Check the estimate before deciding.', 'Maaaring magsimula ito bilang halimbawang tantiya ng app o gamitin ang halagang inilagay mo. Ang blangko ay hindi alam; ang zero ay sinadyang ₱0. Suriin ang tantiya bago magdesisyon.'), aliases: ['transport expense', 'transport cost', 'hauling cost', 'gastos sa biyahe', 'gastos sa transport', 'pamasahe'], routes: ['/places', '/compare'] },
  { id: 'after-transport', topic: 'money', question: q('What does after transport mean?', 'Ano ang ibig sabihin ng after transport?'), answer: q('It is the estimated gross subtotal minus the recorded or entered transport amount. It does not include every farm cost, so it is not profit or take-home pay.', 'Ito ang tinatayang gross subtotal bawas sa nakatalang o inilagay na transport. Hindi kasama ang lahat ng gastos sa bukid, kaya hindi ito tubo o aktuwal na maiuuwi.'), aliases: ['after transport', 'net after transport', 'bawas transport', 'pagkatapos ng transport', 'matitira pagkatapos bumiyahe'], routes: ['/places', '/compare'] },
  { id: 'not-profit', topic: 'money', question: q('Is after transport my profit?', 'Tubo ko na ba ang after transport?'), answer: q('No. It leaves out costs such as production, packaging, loading, fees, and your time. Treat it as a simple comparison estimate only.', 'Hindi. Hindi nito kasama ang gastos sa produksyon, packaging, pagkakarga, bayarin, at oras mo. Simpleng paghahambing na tantiya lang ito.'), aliases: ['not profit', 'is this profit', 'after transport ba ay tubo', 'profit', 'tubo ba', 'kita ba ito'], routes: ['/places', '/compare'] },

  { id: 'distance', topic: 'outlets', question: q('How is distance calculated?', 'Paano kinukuwenta ang layo?'), answer: q('AniWhere currently uses the selected municipality center as the reference point, not your exact farm. When a road-route estimate is available it can show estimated road distance and travel time; otherwise it shows straight-line distance. Neither is a transport quotation.', 'Ginagamit ngayon ng AniWhere ang sentro ng napiling munisipalidad bilang batayang lokasyon, hindi ang eksaktong bukid mo. Kapag may road-route estimate, maaaring ipakita ang tinatayang layo at oras sa kalsada; kung wala, tuwid na layo ang ipinapakita. Hindi transport quotation ang alinman dito.'), aliases: ['distance', 'how far', 'road distance', 'gaano kalayo', 'layo sa outlet', 'municipality center', 'sentro ng munisipyo'], routes: ['/discover', '/places', '/compare'] },
  { id: 'map', topic: 'outlets', question: q('What does the map show?', 'Ano ang ipinapakita ng mapa?'), answer: q('The map compares a municipality-center reference point with possible outlets. Pins also show fit state. Route lines, road distance, and travel time are estimates only when route data is available; confirm the actual road, farm pickup point, access, and receiving point before travel.', 'Inihahambing ng mapa ang sentro ng munisipalidad bilang batayan at ang mga posibleng outlet. Ipinapakita rin ng pins ang fit state. Tantiya lang ang route line, layo sa kalsada, at oras kapag may route data; kumpirmahin ang aktuwal na daan, pickup point sa bukid, access, at receiving point bago bumiyahe.'), aliases: ['map', 'what does map show', 'mapa', 'tingnan ang mapa', 'route map'], routes: ['/','/discover'] },
  { id: 'map-offline', topic: 'outlets', question: q('Will the map work offline?', 'Gagana ba ang mapa offline?'), answer: q('Previously cached AniWhere pages can fall back to the built-in illustrative Laguna map and local data already packaged with the app. Live map tiles and new road-route requests need a connection, so offline distance should not be treated as fresh routing.', 'Kapag na-cache na ang AniWhere, maaaring gumamit ng built-in na guhit-mapa ng Laguna at local data na kasama sa app. Kailangan ng koneksyon ang live map tiles at bagong road-route request, kaya huwag ituring na bagong routing data ang offline na layo.'), aliases: ['map offline', 'offline map', 'mapa offline', 'no internet map', 'gagana offline'], routes: ['/','/discover'] },
  { id: 'updated-valid-until', topic: 'outlets', question: q('What does valid until mean?', 'Ano ang ibig sabihin ng valid until?'), answer: q('It is the date until which the recorded information is intended to apply. It is not a promise that the outlet still has capacity today.', 'Ito ang petsa hanggang kailan dapat gamitin ang nakatalang impormasyon. Hindi ito pangako na may kapasidad pa ang outlet ngayon.'), aliases: ['valid until', 'updated until', 'petsa ng bisa', 'hanggang kailan valid'], routes: ['/discover', '/places'] },
  { id: 'expired-info', topic: 'outlets', question: q('What should I do with an expired price or offer?', 'Ano ang gagawin sa expired na presyo o alok?'), answer: q('Treat it as historical information. Contact the outlet to ask for the current price, capacity, crop condition, and receiving schedule.', 'Ituring itong makasaysayang impormasyon. Kontakin ang outlet para alamin ang kasalukuyang presyo, kapasidad, kondisyon ng pananim, at oras ng pagtanggap.'), aliases: ['expired price', 'expired offer', 'old price', 'expired', 'luma na presyo'], routes: ['/discover', '/places', '/compare'] },
  { id: 'what-to-confirm', topic: 'outlets', question: q('What should I confirm with an outlet?', 'Ano ang dapat kumpirmahin sa outlet?'), answer: q('Confirm that they are receiving your crop, the quantity and quality they can accept, current price, receiving date and hours, exact drop-off point, and any fees or packaging requirements.', 'Kumpirmahin kung tumatanggap sila ng pananim mo, ang dami at kalidad na kaya nila, kasalukuyang presyo, petsa at oras ng pagtanggap, eksaktong drop-off point, at anumang bayarin o packaging requirement.'), aliases: ['what to confirm', 'confirm with buyer', 'ask the outlet', 'ano ang kumpirmahin', 'itatanong sa buyer'], routes: ['/places'] },
  { id: 'prepare-message', topic: 'outlets', question: q('Can AniWhere contact the buyer for me?', 'Makokontak ba ng AniWhere ang buyer para sa akin?'), answer: q('AniWhere prepares a message you can copy. It does not send an SMS, call, or reserve a slot automatically. Send it yourself through your phone and wait for confirmation.', 'Naghahanda ang AniWhere ng mensaheng maaari mong kopyahin. Hindi ito awtomatikong nagse-SMS, tumatawag, o nagre-reserve ng slot. Ikaw ang magpadala gamit ang telepono at maghintay ng kumpirmasyon.'), aliases: ['prepare message', 'contact buyer', 'send message', 'kontakin ang buyer', 'magpadala ng mensahe'], routes: ['/places'] },

  { id: 'save-outlet', topic: 'saved', question: q('How do I save an outlet?', 'Paano mag-save ng outlet?'), answer: q('Use Save on an outlet card or detail page. Saved outlets are kept in this browser so you can review them later.', 'Piliin ang Save sa card o detail page ng outlet. Naka-save ang mga ito sa browser na ito para mabalikan mo sa ibang pagkakataon.'), aliases: ['save outlet', 'save buyer', 'mag-save', 'i-save ang outlet', 'bookmark outlet'], routes: ['/discover', '/places'], action: { label: q('View Saved', 'Tingnan ang Nai-save'), route: '/saved' } },
  { id: 'saved-local', topic: 'saved', question: q('Where are Saved outlets stored?', 'Saan naka-save ang mga outlet?'), answer: q('Saved outlets stay in this browser on this device. They are not a shared account or a buyer message. Clearing browser storage or changing device may remove them.', 'Nananatili ang mga naka-save na outlet sa browser na ito at device na ito. Hindi ito shared account o mensahe sa buyer. Maaaring mawala kapag binura ang browser storage o nagpalit ng device.'), aliases: ['saved local', 'where saved', 'local saved', 'saan naka-save', 'naka-save sa browser'], routes: ['/saved'] },
  { id: 'saved-may-disappear', topic: 'saved', question: q('Why did a Saved outlet disappear?', 'Bakit nawala ang naka-save na outlet?'), answer: q('Saved data is local to this browser. It can disappear after clearing site data, using private browsing, changing devices, or when storage is blocked. Save a note or link if the option matters.', 'Local sa browser ang Saved. Maaaring mawala kapag binura ang site data, gumamit ng private browsing, nagpalit ng device, o hinarangan ang storage. Magtago ng note o link kung mahalaga ang option.'), aliases: ['saved disappeared', 'saved disappear', 'nawala ang saved', 'nawala ang naka-save', 'lost saved'], routes: ['/saved'] },
  { id: 'compare', topic: 'saved', question: q('How does Compare work?', 'Paano gumagana ang Compare?'), answer: q('Choose up to three outlets and compare the same fit, accepted quantity, remaining harvest, price evidence, transport amount, and distance basis. AniWhere does not choose a winner for you; it keeps the tradeoffs visible so you can decide what to confirm next.', 'Pumili ng hanggang tatlong outlet at ihambing ang parehong fit, matatanggap na dami, matitirang ani, ebidensya ng presyo, halaga ng biyahe, at batayan ng layo. Hindi pumipili ng winner ang AniWhere; ipinapakita nito ang tradeoffs para ikaw ang magdesisyon kung ano ang dapat kumpirmahin.'), aliases: ['compare', 'compare outlets', 'paghahambing', 'ikumpara', 'compare buyers'], routes: ['/compare', '/discover'], action: { label: q('Open Compare', 'Buksan ang Compare'), route: '/compare' } },

  { id: 'offline-help', topic: 'offline', question: q('What can I use offline?', 'Ano ang magagamit offline?'), answer: q('After AniWhere has loaded and cached successfully, the bundled FAQ and cached core pages can still help without signal. Offline mode does not create fresh buyer demand, prices, route requests, or online Ani responses; use cached market information only as previously loaded context and confirm it when you reconnect.', 'Kapag matagumpay nang na-load at na-cache ang AniWhere, magagamit pa rin nang walang signal ang bundled FAQ at mga na-cache na pangunahing page. Hindi gumagawa ang offline mode ng bagong buyer demand, presyo, route request, o online Ani response; gamitin lamang ang cached market information bilang dating context at kumpirmahin ito kapag may koneksyon na ulit.'), aliases: ['offline help', 'what works offline', 'magagamit offline', 'walang internet', 'offline aniwhere'], routes: ['*'] },
  { id: 'first-visit-offline', topic: 'offline', question: q('Can I use AniWhere for the first time offline?', 'Magagamit ba ang AniWhere sa unang bukas offline?'), answer: q('No. The first visit needs a connection to load the app and create its cache. Open it once while online if you need help later without data.', 'Hindi. Kailangan ng koneksyon sa unang bukas para ma-load ang app at magawa ang cache. Buksan ito habang online kung kailangan mo itong gamitin nang walang data sa susunod.'), aliases: ['first visit offline', 'first time offline', 'unang bukas offline', 'offline first visit'], routes: ['*'] },
  { id: 'ai-offline', topic: 'offline', question: q('Can online Ani work offline?', 'Gagana ba ang online Ani offline?'), answer: q('No. Local FAQ answers work offline after caching, but online Ani and voice need a connection. You choose when to connect.', 'Hindi. Gumagana offline ang local FAQ pagkatapos ma-cache, pero kailangan ng koneksyon ang online Ani at voice. Ikaw ang pipili kung kailan kokonekta.'), aliases: ['ai offline', 'ani offline', 'voice offline', 'online ani', 'voice walang internet'], routes: ['*'] },
  { id: 'search-language', topic: 'offline', question: q('Can I ask in Filipino or English?', 'Puwede bang Filipino o English ang tanong?'), answer: q('Yes. Ask the local FAQ in Filipino, English, or familiar Taglish. The answer follows your selected language, and the matcher recognizes both.', 'Oo. Magtanong sa Filipino, English, o karaniwang Taglish. Susunod ang sagot sa piniling wika at nakikilala ng matcher ang dalawang wika.'), aliases: ['search language', 'ask in filipino', 'ask in english', 'Filipino question', 'English question', 'puwede taglish'], routes: ['*'] },
  { id: 'refresh-state', topic: 'offline', question: q('Will my harvest state stay after refresh?', 'Mananatili ba ang detalye ng ani kapag nag-refresh?'), answer: q('Harvest details are carried by the page link, so refresh and navigation can keep them when the link is valid. Saved and Compare choices use local browser storage. Keep a copy of an important link.', 'Nasa page link ang detalye ng ani kaya maaaring manatili sa refresh at navigation kapag tama ang link. Gumagamit ng local browser storage ang Saved at Compare. Itago ang importanteng link.'), aliases: ['refresh state', 'after refresh', 'mananatili refresh', 'refresh harvest', 'navigation state'], routes: ['*'] },
  { id: 'data-privacy-local', topic: 'offline', question: q('What happens to my data?', 'Ano ang nangyayari sa data ko?'), answer: q('Local FAQ questions stay in the browser. Saved and Compare choices stay on this device, while harvest details can be included in a shareable URL. If you explicitly use online Ani, your question and relevant app context are sent to the online service.', 'Nananatili sa browser ang tanong sa local FAQ. Nasa device na ito ang Saved at Compare, habang maaaring maisama sa shareable URL ang detalye ng ani. Kapag pinili mong gumamit ng online Ani, ipinapadala sa online service ang tanong at kaugnay na context.'), aliases: ['data privacy', 'where is my data', 'privacy', 'data local', 'pribado ba ang data', 'saan napupunta ang data'], routes: ['*'] },
];

const STOP_WORDS = new Set('a an ang and are ba bakit can do does for how i is it ko may na ng of on the to what when where why with you your sa ang mga paano ano kung ito ang isang'.split(' '));

export function normalizeFaqQuery(value: string): string {
  return value.toLocaleLowerCase().normalize('NFKD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9\s]/g, ' ').replace(/\s+/g, ' ').trim();
}

function tokens(value: string): string[] {
  return normalizeFaqQuery(value).split(' ').filter((token) => token.length > 1 && !STOP_WORDS.has(token));
}

export function matchAniFaq(query: string): FaqMatch {
  const normalized = normalizeFaqQuery(query);
  if (!normalized) return { kind: 'none' };
  const queryTokens = tokens(normalized);
  const scored = ANI_FAQS.map((faq) => {
    const values = [faq.question.en, faq.question.fil, ...faq.aliases].map(normalizeFaqQuery);
    let score = 0;
    if (values.some((value) => value === normalized)) score = 100;
    else if (values.some((value) => value.length >= 9 && normalized.includes(value))) score = 88;
    else {
      const faqTokens = new Set(values.flatMap(tokens));
      const overlap = queryTokens.filter((token) => faqTokens.has(token)).length;
      if (overlap >= 2 || (overlap === 1 && queryTokens.length === 1)) score = 35 + (overlap / Math.max(queryTokens.length, 1)) * 45;
    }
    return { faq, score };
  }).filter((entry) => entry.score > 0).sort((a, b) => b.score - a.score);

  if (!scored.length) return { kind: 'none' };
  const [best, second] = scored;
  if (best.score >= 88 && (!second || best.score - second.score >= 8)) return { kind: 'answer', faq: best.faq, score: best.score };
  if (best.score >= 50) return { kind: 'choices', faqs: scored.slice(0, 3).map((entry) => entry.faq) };
  return { kind: 'none' };
}

export function faqsForRoute(pathname: string): AniFaq[] {
  return ANI_FAQS.filter((faq) => !faq.routes || faq.routes.includes('*') || faq.routes.some((route) => pathname === route || pathname.startsWith(`${route}/`)));
}
