import type { PlaceRecord } from '../lib/domain/types';
import { DEMO_SOURCE_ID } from './demo-sources';

// Every place below is invented for the demo; coordinates indicate sample Laguna locations.
export const DEMO_PLACES: PlaceRecord[] = [
  {
    id: 'demo-cooperative',
    slug: 'demo-cooperative',
    name: 'Ani at Agos Farmers Cooperative',
    category: 'cooperative',
    municipality: 'Santa Cruz',
    lat: 14.281,
    lng: 121.417,
    description: 'Growers’ collection point for graded vegetables and fruit; members consolidate small harvests before morning dispatch.',
    descriptionFil: 'Bagsakan ng mga kasaping magsasaka para sa piniling gulay at prutas; pinagsasama ang maliliit na ani bago bumiyahe sa umaga.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-processor',
    slug: 'demo-processor',
    name: 'Kusina Verde Processing House',
    category: 'processor',
    municipality: 'Calamba',
    lat: 14.214,
    lng: 121.164,
    description: 'Small-batch sauce and puree maker accepting sound processing-grade produce by appointment.',
    descriptionFil: 'Pagawaan ng sarsa at puree na tumatanggap ng maayos na aning pang-proseso ayon sa iskedyul.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-market',
    slug: 'demo-market',
    name: 'Sariwa sa Los Baños Market Collective',
    category: 'market',
    municipality: 'Los Baños',
    lat: 14.18,
    lng: 121.243,
    description: 'Group of public-market stalls sharing a morning receiving area for table-ready produce.',
    descriptionFil: 'Samahan ng mga puwesto sa palengke na may iisang lugar ng pagtanggap sa umaga para sa gulay na pangtinda.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-msme-confirm',
    slug: 'demo-msme-confirm',
    name: 'Timpladong Ani Kitchen',
    category: 'msme',
    municipality: 'San Pablo',
    lat: 14.067,
    lng: 121.325,
    description: 'Farm-to-table prep kitchen taking small batches only when the weekly menu has room.',
    descriptionFil: 'Kusinang naghahanda ng pagkaing mula sa ani; maliit na batch lang kapag may puwang sa lingguhang menu.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-organic-shop',
    slug: 'demo-organic-shop',
    name: 'Dahon at Gulay Café',
    category: 'restaurant',
    municipality: 'Liliw',
    lat: 14.133,
    lng: 121.433,
    description: 'Seasonal café ordering selected vegetables for its daily plates; ask about growing practices before delivery.',
    descriptionFil: 'Café na namimili ng piling gulay para sa araw-araw na putahe; itanong muna ang paraan ng pagtatanim bago maghatid.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-bay-trading',
    slug: 'demo-bay-trading',
    name: 'Bay Luntian Trading Post',
    category: 'market',
    municipality: 'Bay',
    lat: 14.185,
    lng: 121.285,
    description: 'Lakeshore trading point with morning lots for fruit and bundled greens; intake closes when stalls fill.',
    descriptionFil: 'Bagsakan malapit sa lawa para sa prutas at nakataling gulay sa umaga; humihinto ang pagtanggap kapag puno ang mga puwesto.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-pagsanjan-hub',
    slug: 'demo-pagsanjan-hub',
    name: 'Pagsanjan Ilog Harvest Hub',
    category: 'consolidator',
    municipality: 'Pagsanjan',
    lat: 14.275,
    lng: 121.459,
    description: 'Consolidator packing sorted fruit and vegetables into shared truckloads; some batches need advance booking.',
    descriptionFil: 'Tagapagtipon ng piniling prutas at gulay para sa sabayang biyahe ng trak; kailangang magpa-iskedyul para sa ilang batch.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-binan-store',
    slug: 'demo-binan-store',
    name: 'Biñan Sariwa Corner',
    category: 'market',
    municipality: 'Biñan',
    lat: 14.337,
    lng: 121.105,
    description: 'Neighborhood produce store taking smaller, neatly packed daily deliveries rather than truckloads.',
    descriptionFil: 'Tindahan ng gulay sa barangay na tumatanggap ng maliliit at maayos na nakabalot na ani araw-araw, hindi maramihang trak.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-nagcarlan-kitchen',
    slug: 'demo-nagcarlan-kitchen',
    name: 'Nagcarlan Hinog Kitchen',
    category: 'msme',
    municipality: 'Nagcarlan',
    lat: 14.137,
    lng: 121.417,
    description: 'Preserve and snack kitchen whose batch capacity changes with jars and kitchen time.',
    descriptionFil: 'Kusina ng palaman at meryenda; nagbabago ang kayang tanggapin ayon sa garapon at oras ng pagluluto.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-cabuyao-commissary',
    slug: 'demo-cabuyao-commissary',
    name: 'Cabuyao Sangkap Commissary',
    category: 'processor',
    municipality: 'Cabuyao',
    lat: 14.246,
    lng: 121.124,
    description: 'Food-prep commissary buying recipe-specific fruit and vegetables after a sample check.',
    descriptionFil: 'Kusinang naghahanda ng sangkap at bumibili ng prutas at gulay ayon sa resipe matapos suriin ang sample.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
  {
    id: 'demo-victoria-eatery',
    slug: 'demo-victoria-eatery',
    name: 'Silangan Hapunan Eatery',
    category: 'restaurant',
    municipality: 'Victoria',
    lat: 14.23,
    lng: 121.33,
    description: 'Roadside eatery making small same-day purchases for its changing vegetable menu.',
    descriptionFil: 'Karinderya sa tabi ng daan na bumibili ng kaunting sariwang gulay para sa pabago-bagong menu.',
    publicStatus: 'needs_review',
    sourceIds: [DEMO_SOURCE_ID],
  },
];
