import type { PlaceCropCapabilityRecord } from '../lib/domain/types';
import { DEMO_SOURCE_ID } from './demo-sources';

export const DEMO_CAPABILITIES: PlaceCropCapabilityRecord[] = [
  {
    id: 'cap-demo-cooperative-tomato',
    placeId: 'demo-cooperative',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Confirm crate cleanliness', 'Receiving 6:00 AM to 11:00 AM'],
    conditionsFil: ['Kumpirmahin ang kalinisan ng kahon', 'Pagtanggap 6:00 AM hanggang 11:00 AM'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-cooperative-eggplant',
    placeId: 'demo-cooperative',
    cropKey: 'eggplant',
    acceptanceState: 'accepted',
    conditions: ['Confirm sorting by length'],
    conditionsFil: ['Kumpirmahin ang paghihiwalay ayon sa haba'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-cooperative-calamansi',
    placeId: 'demo-cooperative',
    cropKey: 'calamansi',
    acceptanceState: 'accepted',
    conditions: ['Green skin, uniform size'],
    conditionsFil: ['Berdeng balat, magkakaparehong laki'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-processor-tomato',
    placeId: 'demo-processor',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Processing grade acceptable', 'Delivery scheduling required prior to dispatch'],
    conditionsFil: ['Pang-proseso na kalidad ay tinatanggap', 'Kailangang magpa-iskedyul bago ibiyahe'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-processor-eggplant',
    placeId: 'demo-processor',
    cropKey: 'eggplant',
    acceptanceState: 'accepted',
    conditions: ['Firm skin without rot'],
    conditionsFil: ['Matigas na balat, walang sira'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-market-tomato',
    placeId: 'demo-market',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Table ripe grade 1', 'Confirm remaining stall capacity'],
    conditionsFil: ['Pang-mesa Hinog Klasik 1', 'Kumpirmahin ang natitirang espasyo sa pwesto'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-market-calamansi',
    placeId: 'demo-market',
    cropKey: 'calamansi',
    acceptanceState: 'accepted',
    conditions: ['Freshly harvested within 24h'],
    conditionsFil: ['Bagong pitas sa loob ng 24 oras'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-msme-tomato',
    placeId: 'demo-msme-confirm',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Contact to confirm batch size'],
    conditionsFil: ['Makipag-ugnayan para sa laki ng batch'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-organic-tomato',
    placeId: 'demo-organic-shop',
    cropKey: 'tomato',
    acceptanceState: 'excluded',
    conditions: [],
    conditionsFil: [],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-organic-eggplant',
    placeId: 'demo-organic-shop',
    cropKey: 'eggplant',
    acceptanceState: 'accepted',
    conditions: ['Certified pesticide-free'],
    conditionsFil: ['Walang kemikal'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
];
