import type { PlaceCropCapabilityRecord } from '../lib/domain/types';
import { DEMO_SOURCE_ID } from './demo-sources';

// Fictional demo evidence, not verification of a real buyer.
const DEMO_EVIDENCE = { verifiedAt: '2026-09-17T08:00:00+08:00', sourceId: DEMO_SOURCE_ID };

export const DEMO_CAPABILITIES: PlaceCropCapabilityRecord[] = [
  {
    id: 'cap-demo-cooperative-tomato',
    placeId: 'demo-cooperative',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Confirm crate cleanliness', 'Receiving 6:00 AM to 11:00 AM'],
    conditionsFil: ['Kumpirmahin ang kalinisan ng kahon', 'Pagtanggap 6:00 AM hanggang 11:00 AM'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-cooperative-eggplant',
    placeId: 'demo-cooperative',
    cropKey: 'eggplant',
    acceptanceState: 'accepted',
    conditions: ['Confirm sorting by length'],
    conditionsFil: ['Kumpirmahin ang paghihiwalay ayon sa haba'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-cooperative-calamansi',
    placeId: 'demo-cooperative',
    cropKey: 'calamansi',
    acceptanceState: 'accepted',
    conditions: ['Green skin, uniform size'],
    conditionsFil: ['Berdeng balat, magkakaparehong laki'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-processor-tomato',
    placeId: 'demo-processor',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Processing grade acceptable', 'Delivery scheduling required prior to dispatch'],
    conditionsFil: ['Pang-proseso na kalidad ay tinatanggap', 'Kailangang magpa-iskedyul bago ibiyahe'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-processor-eggplant',
    placeId: 'demo-processor',
    cropKey: 'eggplant',
    acceptanceState: 'accepted',
    conditions: ['Firm skin without rot'],
    conditionsFil: ['Matigas na balat, walang sira'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-market-tomato',
    placeId: 'demo-market',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Table ripe grade 1', 'Confirm remaining stall capacity'],
    conditionsFil: ['Pang-mesa Hinog Klasik 1', 'Kumpirmahin ang natitirang espasyo sa pwesto'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-market-calamansi',
    placeId: 'demo-market',
    cropKey: 'calamansi',
    acceptanceState: 'accepted',
    conditions: ['Freshly harvested within 24h'],
    conditionsFil: ['Bagong pitas sa loob ng 24 oras'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-msme-tomato',
    placeId: 'demo-msme-confirm',
    cropKey: 'tomato',
    acceptanceState: 'accepted',
    conditions: ['Contact to confirm batch size'],
    conditionsFil: ['Makipag-ugnayan para sa laki ng batch'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-organic-tomato',
    placeId: 'demo-organic-shop',
    cropKey: 'tomato',
    acceptanceState: 'excluded',
    conditions: [],
    conditionsFil: [],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-organic-eggplant',
    placeId: 'demo-organic-shop',
    cropKey: 'eggplant',
    acceptanceState: 'accepted',
    conditions: ['Certified pesticide-free'],
    conditionsFil: ['Walang kemikal'],
    verifiedAt: '2026-09-17T08:00:00+08:00',
    sourceId: DEMO_SOURCE_ID,
  },
  {
    id: 'cap-demo-cooperative-banana', placeId: 'demo-cooperative', cropKey: 'banana', acceptanceState: 'accepted',
    conditions: ['Separate bruised fingers before loading'], conditionsFil: ['Ihiwalay ang napisang saging bago ikarga'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-pagsanjan-banana', placeId: 'demo-pagsanjan-hub', cropKey: 'banana', acceptanceState: 'accepted',
    conditions: ['Deliver by bunch, with cut ends covered'], conditionsFil: ['Ihatid nang buwig, nakatakip ang pinutulang dulo'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-binan-banana', placeId: 'demo-binan-store', cropKey: 'banana', acceptanceState: 'accepted',
    conditions: ['Small ripe batches only'], conditionsFil: ['Maliit na batch ng hinog na saging lamang'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-nagcarlan-banana', placeId: 'demo-nagcarlan-kitchen', cropKey: 'banana', acceptanceState: 'accepted',
    conditions: ['Confirm jar production before harvesting'], conditionsFil: ['Kumpirmahin ang iskedyul ng paggawa ng palaman bago mag-ani'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-cabuyao-banana', placeId: 'demo-cabuyao-commissary', cropKey: 'banana', acceptanceState: 'excluded',
    conditions: ['No banana recipe in this sample cycle'], conditionsFil: ['Walang resipe ng saging sa halimbawang siklong ito'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-cooperative-papaya', placeId: 'demo-cooperative', cropKey: 'papaya', acceptanceState: 'accepted',
    conditions: ['Pack mature-green fruit apart from ripe fruit'], conditionsFil: ['Ihiwalay ang hinog sa gulang na berdeng papaya'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-bay-papaya', placeId: 'demo-bay-trading', cropKey: 'papaya', acceptanceState: 'accepted',
    conditions: ['Cushion fruit in crates to avoid bruising'], conditionsFil: ['Lagyan ng panangga ang prutas sa kahon upang hindi mapasâ'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-nagcarlan-papaya', placeId: 'demo-nagcarlan-kitchen', cropKey: 'papaya', acceptanceState: 'accepted',
    conditions: ['Confirm ripeness and open kitchen batch'], conditionsFil: ['Kumpirmahin ang pagkahinog at bakanteng batch sa kusina'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-victoria-papaya', placeId: 'demo-victoria-eatery', cropKey: 'papaya', acceptanceState: 'accepted',
    conditions: ['Only green papaya for the daily menu; ask for the price'],
    conditionsFil: ['Berdeng papaya lang para sa pang-araw-araw na menu; itanong ang presyo'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-cabuyao-papaya', placeId: 'demo-cabuyao-commissary', cropKey: 'papaya', acceptanceState: 'accepted',
    conditions: ['Ripe papaya only; sample check before delivery'],
    conditionsFil: ['Hinog na papaya lang; ipasuri ang sample bago maghatid'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-binan-papaya', placeId: 'demo-binan-store', cropKey: 'papaya', acceptanceState: 'excluded',
    conditions: ['No papaya shelf space in the sample plan'], conditionsFil: ['Walang puwesto para sa papaya sa halimbawang plano'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-market-pechay', placeId: 'demo-market', cropKey: 'pechay', acceptanceState: 'accepted',
    conditions: ['Keep leaves shaded until morning receiving'], conditionsFil: ['Ilagay sa lilim ang dahon hanggang sa pagtanggap sa umaga'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-binan-pechay', placeId: 'demo-binan-store', cropKey: 'pechay', acceptanceState: 'accepted',
    conditions: ['Bundle by size; no yellow leaves'], conditionsFil: ['Itali ayon sa laki; walang naninilaw na dahon'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-bay-pechay', placeId: 'demo-bay-trading', cropKey: 'pechay', acceptanceState: 'accepted',
    conditions: ['Deliver before the midday heat'], conditionsFil: ['Ihatid bago ang matinding init ng tanghali'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-victoria-pechay', placeId: 'demo-victoria-eatery', cropKey: 'pechay', acceptanceState: 'accepted',
    conditions: ['Same-day leaves only; price to be agreed'], conditionsFil: ['Dahong pinitas sa araw ding iyon; pag-usapan muna ang presyo'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-nagcarlan-pechay', placeId: 'demo-nagcarlan-kitchen', cropKey: 'pechay', acceptanceState: 'unknown',
    conditions: ['Ask whether the menu needs leafy greens'], conditionsFil: ['Itanong kung kailangan ng madahong gulay sa menu'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-cabuyao-pechay', placeId: 'demo-cabuyao-commissary', cropKey: 'pechay', acceptanceState: 'excluded',
    conditions: ['Leafy greens are not processed here in this sample'],
    conditionsFil: ['Hindi pinoproseso rito ang madahong gulay sa halimbawang ito'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-bay-sitaw', placeId: 'demo-bay-trading', cropKey: 'sitaw', acceptanceState: 'accepted',
    conditions: ['Tie straight pods in loose bundles'], conditionsFil: ['Itali nang maluwag ang tuwid na bunga'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-binan-sitaw', placeId: 'demo-binan-store', cropKey: 'sitaw', acceptanceState: 'accepted',
    conditions: ['No wilted pods; pack in ventilated baskets'],
    conditionsFil: ['Walang lantang bunga; ilagay sa maaliwalas na basket'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-pagsanjan-sitaw', placeId: 'demo-pagsanjan-hub', cropKey: 'sitaw', acceptanceState: 'accepted',
    conditions: ['Truck space is assigned only after a call'], conditionsFil: ['Itinatakda lamang ang puwesto sa trak pagkatapos tumawag'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-victoria-sitaw', placeId: 'demo-victoria-eatery', cropKey: 'sitaw', acceptanceState: 'accepted',
    conditions: ['Small kitchen batches; confirm price on arrival'],
    conditionsFil: ['Maliit na batch para sa kusina; kumpirmahin ang presyo pagdating'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-cabuyao-sitaw', placeId: 'demo-cabuyao-commissary', cropKey: 'sitaw', acceptanceState: 'excluded',
    conditions: ['No sitaw in the sample prep schedule'], conditionsFil: ['Walang sitaw sa halimbawang iskedyul ng paghahanda'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-bay-tomato', placeId: 'demo-bay-trading', cropKey: 'tomato', acceptanceState: 'accepted',
    conditions: ['Separate firm from soft fruit for stall sales'], conditionsFil: ['Ihiwalay ang matigas sa malambot na bunga para sa puwesto'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-binan-tomato', placeId: 'demo-binan-store', cropKey: 'tomato', acceptanceState: 'accepted',
    conditions: ['Table-ripe only in stackable crates'], conditionsFil: ['Pang-mesang hinog lang sa patung-patong na kahon'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-cabuyao-tomato', placeId: 'demo-cabuyao-commissary', cropKey: 'tomato', acceptanceState: 'accepted',
    conditions: ['Confirm recipe grade and batch availability'],
    conditionsFil: ['Kumpirmahin ang klaseng kailangan sa resipe at bakanteng batch'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-pagsanjan-eggplant', placeId: 'demo-pagsanjan-hub', cropKey: 'eggplant', acceptanceState: 'accepted',
    conditions: ['Pack firm eggplant in shallow crates'], conditionsFil: ['Ilagay ang matibay na talong sa mababaw na kahon'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-victoria-eggplant', placeId: 'demo-victoria-eatery', cropKey: 'eggplant', acceptanceState: 'accepted',
    conditions: ['Short same-day kitchen order'], conditionsFil: ['Maliit na order para sa kusina sa araw ding iyon'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-nagcarlan-calamansi', placeId: 'demo-nagcarlan-kitchen', cropKey: 'calamansi', acceptanceState: 'accepted',
    conditions: ['Clean, firm fruit for preserves'], conditionsFil: ['Malinis at matibay na prutas para sa palaman'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-cabuyao-calamansi', placeId: 'demo-cabuyao-commissary', cropKey: 'calamansi', acceptanceState: 'accepted',
    conditions: ['Request sample for juice yield before booking'],
    conditionsFil: ['Magpasa ng sample para sa dami ng katas bago magpa-iskedyul'],
    ...DEMO_EVIDENCE,
  },
  {
    id: 'cap-demo-victoria-calamansi', placeId: 'demo-victoria-eatery', cropKey: 'calamansi', acceptanceState: 'unknown',
    conditions: ['Ask whether the menu needs calamansi'], conditionsFil: ['Itanong kung kailangan ng kalamansi sa menu'],
    ...DEMO_EVIDENCE,
  },
];
