import type { Outlet } from '../lib/domain/types';

const DEMO_SOURCE = {
  sourceKind: 'demo' as const,
  sourceLabel: 'Demo — sample data',
  lastUpdatedAt: '2026-09-17T08:00:00+08:00',
  validFrom: '2026-09-17',
  validUntil: '2026-09-30',
  offerStatus: 'active' as const,
};

export const DEMO_OUTLETS: Outlet[] = [
  {
    id: 'demo-cooperative',
    slug: 'demo-cooperative',
    name: 'Demo Cooperative',
    category: 'cooperative',
    municipality: 'Santa Cruz',
    lat: 14.281,
    lng: 121.417,
    description:
      'Farmer-owned cooperative aggregation facility. Consolidates member and partner harvests for regional food terminals.',
    descriptionFil:
      'Pasilidad ng kooperatiba ng mga magsasaka. Pinagsasama-sama ang ani para sa mga rehiyonal na bagsakan.',
    sampleOfferDate: '17 Sep 2026',
    isDemoFixture: true,
    acceptedCrops: {
      tomato: {
        maxKg: 500,
        pricePerKg: 28,
        defaultTransportExpense: 600,
        conditions: ['Confirm crate cleanliness', 'Receiving 6:00 AM to 11:00 AM'],
        conditionsFil: ['Kumpirmahin ang kalinisan ng kahon', 'Pagtanggap 6:00 AM hanggang 11:00 AM'],
        isActive: true,
        ...DEMO_SOURCE,
      },
      eggplant: {
        maxKg: 300,
        pricePerKg: 25,
        defaultTransportExpense: 600,
        conditions: ['Confirm sorting by length'],
        conditionsFil: ['Kumpirmahin ang paghihiwalay ayon sa haba'],
        isActive: true,
        ...DEMO_SOURCE,
      },
      calamansi: {
        maxKg: 200,
        pricePerKg: 45,
        defaultTransportExpense: 600,
        conditions: ['Green skin, uniform size'],
        conditionsFil: ['Berdeng balat, magkakaparehong laki'],
        isActive: true,
        ...DEMO_SOURCE,
      },
    },
  },
  {
    id: 'demo-processor',
    slug: 'demo-processor',
    name: 'Demo Processor',
    category: 'processor',
    municipality: 'Calamba',
    lat: 14.214,
    lng: 121.164,
    description:
      'Local agricultural sauce and puree manufacturing facility. High-volume seasonal processing plant.',
    descriptionFil:
      'Lokal na pagawaan ng sarsa at puree. Tumatanggap ng maramihang ani para sa pagpoproseso.',
    sampleOfferDate: '17 Sep 2026',
    isDemoFixture: true,
    acceptedCrops: {
      tomato: {
        maxKg: 1000,
        pricePerKg: 32,
        defaultTransportExpense: 300,
        conditions: ['Processing grade acceptable', 'Delivery scheduling required prior to dispatch'],
        conditionsFil: ['Pang-proseso na kalidad ay tinatanggap', 'Kailangang magpa-iskedyul bago ibiyahe'],
        isActive: true,
        ...DEMO_SOURCE,
      },
      eggplant: {
        maxKg: 200,
        pricePerKg: 22,
        defaultTransportExpense: 300,
        conditions: ['Firm skin without rot'],
        conditionsFil: ['Matigas na balat, walang sira'],
        isActive: true,
        ...DEMO_SOURCE,
      },
    },
  },
  {
    id: 'demo-market',
    slug: 'demo-market',
    name: 'Demo Market',
    category: 'market',
    municipality: 'Los Baños',
    lat: 14.18,
    lng: 121.243,
    description:
      'Municipal trading hub and public market stall association with daily direct consumer demand.',
    descriptionFil:
      'Bagsakan at pampublikong pamilihan ng bayan na may pang-araw-araw na mamimili.',
    sampleOfferDate: '17 Sep 2026',
    isDemoFixture: true,
    acceptedCrops: {
      tomato: {
        maxKg: 200,
        pricePerKg: 30,
        defaultTransportExpense: 300,
        conditions: ['Table ripe grade 1', 'Confirm remaining stall capacity'],
        conditionsFil: ['Pang-mesa Hinog Klasik 1', 'Kumpirmahin ang natitirang espasyo sa pwesto'],
        isActive: true,
        ...DEMO_SOURCE,
      },
      calamansi: {
        maxKg: 150,
        pricePerKg: 48,
        defaultTransportExpense: 300,
        conditions: ['Freshly harvested within 24h'],
        conditionsFil: ['Bagong pitas sa loob ng 24 oras'],
        isActive: true,
        ...DEMO_SOURCE,
      },
    },
  },
  {
    id: 'demo-msme-confirm',
    slug: 'demo-msme-confirm',
    name: 'Demo MSME (Confirm Capacity)',
    category: 'msme',
    municipality: 'San Pablo',
    lat: 14.067,
    lng: 121.325,
    description:
      'Specialty culinary workshop and farm-to-table kitchen. Capacity fluctuates based on weekly orders.',
    descriptionFil:
      'Kusina at pagawaan ng lutuin. Pabago-bago ang dami depende sa lingguhang order.',
    sampleOfferDate: '17 Sep 2026',
    isDemoFixture: true,
    acceptedCrops: {
      tomato: {
        pricePerKg: 35,
        defaultTransportExpense: 400,
        conditions: ['Contact to confirm batch size'],
        conditionsFil: ['Makipag-ugnayan para sa laki ng batch'],
        isActive: true,
        ...DEMO_SOURCE,
      },
    },
  },
  {
    id: 'demo-organic-shop',
    slug: 'demo-organic-shop',
    name: 'Demo Organic Shop',
    category: 'restaurant',
    municipality: 'Liliw',
    lat: 14.133,
    lng: 121.433,
    description: 'High-end salad bar and organic provisions shop.',
    descriptionFil: 'Tindahan ng mga organikong gulay at sangkap.',
    sampleOfferDate: '17 Sep 2026',
    isDemoFixture: true,
    excludedCrops: ['tomato'],
    acceptedCrops: {
      eggplant: {
        maxKg: 100,
        pricePerKg: 40,
        conditions: ['Certified pesticide-free'],
        conditionsFil: ['Walang kemikal'],
        isActive: true,
        ...DEMO_SOURCE,
      },
    },
  },
];
